### PR TITLE
Add integration tests for keypress

### PR DESCRIPTION
**Pull request by TheKaterTot**
Since I encountered a slight bug when I used this module (which I think you already fixed), I thought tests could help keep track of performance. I used karma and karma-browserify to write integration tests to check for key presses. 

Triggering the keypress in the test was tough--I found some ways to do it with jquery, but I didn't want to bring in the whole library just for the test. Eventually, I found a method that works without it.

Let me know what you think!

### CODE REVIEW

**Comment by bthesorceror** [comment]
Could you please add a npm test script so that travis can be added to this project, please keep in mind that karma start will not work as it keeps the tests running and running the tests need to end for travis.

**Comment by TheKaterTot** [comment]
I can do that 👍

**Comment by TheKaterTot** [comment]
I added a script for a single run of karma. Now, you can run npm test, which should work for Travis

**Comment by bthesorceror** [comment]
LGTM

**Pull request merged**
